wandb_version: 1

training_set:
  desc: null
  value: generalization/training
validation_sets:
  desc: null
  value:
  - generalization/Grid_Size
  - generalization/N_Shape
  - generalization/Shape_Size
  - generalization/Transforms
  - generalization/Right_Transforms
  - generalization/Composition
  - generalization/in_distribution
user:
  desc: null
  value: arcworld
project:
  desc: null
  value: generalization_benchmark
model:
  desc: null
  value: modified
wandb_run_name:
  desc: null
  value: generalization_1
wandb_notes:
  desc: null
  value: null
pos_encoding:
  desc: null
  value: 2D
embedding:
  desc: null
  value: conv
embedding_scaling:
  desc: null
  value: 1
epochs:
  desc: null
  value: 30
bs:
  desc: null
  value: 16
device:
  desc: null
  value: cuda
optim:
  desc: null
  value:
    lr: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698508757.048382
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      2:
      - 1
      - 41
      - 50
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
