defaults:
  - _self_
  - dataset: translate_rotate
  - optim: adamw
  - model: pixeltransformer

user: arcworld
project: pixeltransformer
epochs: 1
bs: 4
device: cuda
wandb_notes: ???
wandb_run_name: ???
rank: ??? # DON'T CHANGE THIS: use always the command line arguments.
world_size: ??? # DON'T CHANGE THIS: use always the command line arguments.
