defaults:
  - _self_
  - optim: adamw
  - dataset: generalization_translate

user: arcworld
project: generalization_benchmark
model: modified
wandb_run_name: generalization_2_full90k
wandb_notes:
pos_encoding: 2D
embedding: conv
embedding_scaling: 2
epochs: 30
bs: 32
device: cuda
