defaults:
  - _self_
  - dataset: single_translate_5by5
  - optim: adamw

user: arcworld
project: stormer
model: modified
wandb_run_name: single_translate_5by5
wandb_notes: "trying 1d pos encoding"
pos_encoding: 1D
embedding: conv
embedding_scaling: 1
epochs: 15
bs: 64
device: cuda
