defaults:
  - _self_
  - dataset: single_translate_5by5
  - optim: adamw

user: arcworld
project: stormer
wandb_run_name: single_translate_5by5
wandb_notes: "trying 1d pos encoding"
pos_encoding: 2D
epochs: 10
bs: 64
device: cuda
