defaults:
  - _self_
  - dataset: single_translate_5by5
  - optim: adamw

user: arcworld
project: stormer
model: modified
wandb_run_name: single_translate_modified_model
wandb_notes: ""
pos_encoding: 2D
embedding: conv
epochs: 15
bs: 64
device: cuda
