defaults:
  - _self_
  - optim: adamw

training_set: generalization/training

validation_sets:
  - generalization/Grid_Size
  - generalization/N_Shape
  - generalization/Shape_Size
  - generalization/Transforms
  - generalization/Right_Transforms
  - generalization/Composition
  - generalization/in_distribution

user: arcworld
project: generalization_benchmark
model: modified
wandb_run_name: generalization_1
wandb_notes:
pos_encoding: 2D
embedding: conv
embedding_scaling: 1
epochs: 30
bs: 16
device: cuda
